import = [
	"~/.config/alacritty/themes/catppuccin-mocha.toml",
]

live_config_reload = false

[window]
option_as_alt = "Both"
padding = { x = 4, y = 4 }

[font]
size = 14
normal = { family = "MonoLisa Nerd Font", style = "Regular" }
bold = { style = "Medium Regular" }
bold_italic = { style = "Medium Italic" }
offset = { x = 0, y = 2 }
